version: "3"
services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    volumes:
      - ./swagger.yaml:/swagger/swagger.yaml
    environment:
      - SWAGGER_JSON=/swagger/swagger.yaml
